import type { Metadata } from "next";
import { ThemeProvider } from "@/components/theme-provider" 
import "./globals.css";
import { cn } from "@/lib/utils";
import { firaSans } from "./fonts/font";

export const metadata: Metadata = {
  title: "ampm web flyer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(firaSans.className, 'no-scrollbar')}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          disableTransitionOnChange
        >
          {children}  
        </ThemeProvider>
      </body>
    </html>
  );
}
